/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  integration: process.env.REACT_APP_INTTEGRATION,
  tt: process.env.REACT_APP_TT,
  version: process.env.REACT_APP_VERSION,
};

export default ebconfig;
