/* eslint-disable */
// WARNING: Do not edit this file
import env from "react-dotenv";

// const ebconfig = {
//   "integration": "",
//   "tt": "tt-1-RKOZW233u39Wci4FPAeMCgiFiqnFq5W6AdGQc5wZZao=",
//   "version": "2020-11-20"
// }

// export default ebconfig;

console.log("intergration: ", process.env)
const ebconfig = {
  "integration": process.env.REACT_APP_INTTEGRATION,
  "tt": process.env.REACT_APP_TT,
  "version": process.env.REACT_APP_VERSION
}

export default ebconfig;