// /* eslint-disable */
// // WARNING: Do not edit this file

// const ebconfig = {
//   integration: process.env.REACT_APP_INTTEGRATION,
//   tt: process.env.REACT_APP_TT,
//   version: process.env.REACT_APP_VERSION,
// };
// console.log("integration: ", ebconfig.integration);

// export default ebconfig;

/* eslint-disable */
// WARNING: Do not edit this file

// const ebconfig = {
//   integration:
//     "react-1-w-2xRFba9dhSOEDHLSyW-ZC24pMvu9bZH1L9HHK-MzvrtSJgF0oTjasCZUQt--If5PPkvs5dxb813udFvKNlCfvrARvRWnh94UqV-zZBoPzwJUJfL28Z-8bx",
//   tt: "tt-1-j30MDuuEOvZYl6pyQyg6TsEnmhtsfB7T4YvZFIoIN38=",
//   version: "2020-11-20",
// };

// export default ebconfig;

import * as contentful from "contentful";

export const client = contentful.createClient({
  space: "u8fg41n0p7cy",
  accessToken: "WBybSjJHJaOm49D7yJAc2vsccohObZqJHyoMm7TJxfo",
});
